google/cloud/firestore_v1/transaction.py, tests/unit/v1/test_transaction.py
=> fix(firestore): fix get and getall method of transaction

tests/unit/v1/test_order.py, tests/unit/v1beta1/test_order.py
Fixes #47 
This PR fixes a lint error that recently started occurring on master out of the blue.
**How to verify**
Run the lint check on master:
$ nox -f noxfile.py -s lint
=> fix(firestore): fix lint

google/cloud/firestore_v1/collection.py, google/cloud/firestore_v1/query.py, tests/unit/v1/test_collection.py, tests/unit/v1/test_query.py
Pushing an implementation with de-deprecation of the `get()` method (as @BenWhitehead mentioned).
=> feat: support limit to last feature

google/cloud/firestore_v1/base_transaction.py, google/cloud/firestore_v1/transaction.py, tests/unit/v1/test_base_transaction.py, tests/unit/v1/test_transaction.py
=> refactor: create base transaction class

tests/unit/v1/test_query.py
Removes dependency on `six` package as Python2 is no longer supported. Towards #94
=> fix: remove six dependency

google/cloud/firestore_v1/async_document.py, google/cloud/firestore_v1/async_transaction.py
=> refactor: drop six dependency

tests/unit/v1/test_async_collection.py, tests/unit/v1/test_async_document.py, tests/unit/v1/test_async_query.py, tests/unit/v1/test_base_collection.py, tests/unit/v1/test_base_document.py, tests/unit/v1/test_collection.py, tests/unit/v1/test_document.py, tests/unit/v1/test_query.py
=> fix: constructor invalid path tests

tests/unit/v1/test_async_query.py, tests/unit/v1/test_query.py
=> fix: add mocks to query get test

google/cloud/firestore_v1/async_client.py, google/cloud/firestore_v1/base_client.py, google/cloud/firestore_v1/client.py, noxfile.py, tests/unit/v1/test__helpers.py, tests/unit/v1/test_async_client.py
=> feat: asyncio microgen client

google/cloud/firestore_v1/async_collection.py, tests/unit/v1/test_async_client.py, tests/unit/v1/test_async_collection.py
=> feat: asyncio microgen collection

google/cloud/firestore_v1/async_collection.py, google/cloud/firestore_v1/async_document.py, google/cloud/firestore_v1/document.py, tests/unit/v1/test_async_client.py, tests/unit/v1/test_async_collection.py, tests/unit/v1/test_async_document.py
=> feat: asyncio microgen document

google/cloud/firestore_v1/async_client.py, tests/unit/v1/test__helpers.py, tests/unit/v1/test_async_client.py, tests/unit/v1/test_async_collection.py
=> fix: asyncio microgen client get_all type

google/cloud/firestore_v1/async_client.py, google/cloud/firestore_v1/async_query.py, tests/unit/v1/test__helpers.py, tests/unit/v1/test_async_client.py, tests/unit/v1/test_async_collection.py, tests/unit/v1/test_async_query.py
=> feat: asyncio microgen query

google/cloud/firestore_v1/async_document.py
Adds missing `await`s to document docs. All other async docs do not have this issue.
=> fix: asyncio document docs

.gitignore, google/cloud/firestore_v1/base_client.py
Adds pytype to gitignore and fixes the following:
```
[47/63] check base_client
FAILED: /home/rafilong/workspace/googleapis/python-firestore/.pytype/pyi/base_client.pyi 
/home/rafilong/workspace/googleapis/python-firestore/.nox/pytype/bin/python -m pytype.single --disable pyi-error --imports_info /home/rafilong/workspace/googleapis/python-firestore/.pytype/imports/base_client.imports --module-name base_client -V 3.8 -o /home/rafilong/workspace/googleapis/python-firestore/.pytype/pyi/base_client.pyi --analyze-annotated --nofail --quick /home/rafilong/workspace/googleapis/python-firestore/google/cloud/firestore_v1/__pycache__/base_client.py
File "/home/rafilong/workspace/googleapis/python-firestore/google/cloud/firestore_v1/__pycache__/base_client.py", line 37, in <module>: Can't find …
```
=> fix: pytype client errors

google/cloud/firestore_v1/async_collection.py, google/cloud/firestore_v1/async_query.py, google/cloud/firestore_v1/base_collection.py, google/cloud/firestore_v1/base_query.py, google/cloud/firestore_v1/collection.py, google/cloud/firestore_v1/query.py, tests/unit/v1/test_async_collection.py, tests/unit/v1/test_async_query.py, tests/unit/v1/test_base_collection.py, tests/unit/v1/test_collection.py, tests/unit/v1/test_query.py
Integrate changes from #57 to the async client.
=> feat: integrate limit to last

google/cloud/firestore_v1/async_transaction.py, tests/unit/v1/test_async_transaction.py
Expected usecase of `AsyncTransactional` is as follows, update implementation to await wrapped function.
```
async def update_data_transaction():
db = firestore.AsyncClient()
transaction = db.transaction()
city_ref = db.collection(u'cities').document(u'SF')
@firestore.async_transactional
async def update_in_transaction(transaction, city_ref):
snapshot = await city_ref.get(transaction=transaction)
transaction.update(city_ref, {
u'population': snapshot.get(u'population') + 1
})
await update_in_transaction(transaction, city_ref)
```
=> fix: async transactional

google/cloud/firestore_v1/client.py, setup.py, tests/unit/v1/test_client.py
=> feat(firestore): add client_options to base class

CHANGELOG.md
=> docs: re-add changelog entries lost in V2 switch

google/cloud/firestore_v1/base_query.py
Towards #56 
From the comment of PR https://github.com/googleapis/python-firestore/pull/58#issuecomment-677846658
=> fix: use specific naming convention

google/cloud/firestore.py, google/cloud/firestore_v1/__init__.py, google/cloud/firestore_v1/async_client.py, google/cloud/firestore_v1/async_query.py, google/cloud/firestore_v1/base_query.py, google/cloud/firestore_v1/client.py, google/cloud/firestore_v1/query.py, tests/system/test_system.py, tests/system/test_system_async.py, tests/unit/v1/test_async_query.py, tests/unit/v1/test_base_query.py, tests/unit/v1/test_query.py
Implement the new partition queries feature for Firestore.
=> feat: partition queries

google/cloud/firestore_v1/_helpers.py, google/cloud/firestore_v1/async_client.py, google/cloud/firestore_v1/async_document.py, google/cloud/firestore_v1/base_client.py, google/cloud/firestore_v1/base_document.py, google/cloud/firestore_v1/client.py, google/cloud/firestore_v1/document.py, tests/unit/v1/test__helpers.py, tests/unit/v1/test_async_client.py, tests/unit/v1/test_async_document.py, tests/unit/v1/test_async_query.py, tests/unit/v1/test_client.py, tests/unit/v1/test_document.py, tests/unit/v1/test_order.py
Note that the synthtool-generated `.coveragerc` (see #224) does *not* include all changes needed for 100% coverage:  see:
- https://github.com/googleapis/gapic-generator-python/issues/171
- https://github.com/googleapis/gapic-generator-python/issues/437
Closes #92.
Closes #195.
=> chore: restore coverage (almost) to 100%

.coveragerc, google/cloud/firestore_v1/base_client.py, synth.py
- Ignore 'DistributionNotFound' fallbacks (only in setuptools-less installs).
- Drop unused helper (fossil from PR #225).
See #92.
release-as: 2.0.0-dev2
=> tests: restore 100% coverage

CHANGELOG.md
Remove spurious Reverts section (all ancient commits unrelated to this release).
Tweak markdown, language.
See #235.
=> chore: repair changelog

docs/index.rst, google/cloud/firestore_v1/base_client.py, noxfile.py, tests/unit/v1/test_base_client.py
As part of the migration to the new generator, the method for creating insecure_channels was removed. Bring back insecure channel creation for emulators.
Fixes #250
=> fix: use an insecure channel under emulation

google/cloud/firestore_v1/base_client.py, tests/unit/v1/test_base_client.py
This changes the `grpc.Channel` used when connecting to a local emulator so that the client credentials are used. This allows for testing database rules against the emulator in python.
Fixes #https://github.com/googleapis/python-firestore/issues/268 
thanks
=> feat: support using client credentials with emulator

google/cloud/firestore_v1/base_collection.py, tests/unit/v1/test_async_collection.py, tests/unit/v1/test_collection.py
As we don't use any of the field data as part of list_documents, we can exclude it from the request/wire :)
Fixes #5 🦕
=> fix: limit data transferred as part of list_documents as we don't require field data

tests/system/test_system.py
Adds a system test demonstrating that ArrayUnion operation no longer deletes pre-existing data
Fixes #14 🦕
=> tests: add system test to verify ArrayUnion upserts

docs/batch.rst, docs/client.rst, docs/collection.rst, docs/document.rst, docs/query.rst, docs/transaction.rst, google/cloud/firestore_v1/base_collection.py, google/cloud/firestore_v1/base_query.py, google/cloud/firestore_v1/document.py
Also, re-document classes lost in async split.
Closes #277.
=> docs: clarify semantics of 'merge' argument to 'Document.set'

synth.py
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
=> docs: trailing whitespace in contributing.rst
